<?php

define('GEONETNZ_ENDPOINT', 'http://magma.geonet.org.nz/services/quake/quakeml/1.0.1/query');
/**
 * Examples of QuakeML queries
http://www.geonet.org.nz/resources/earthquake/quake-web-services.html
Earthquake information for the specified reference number 2737452:

http://magma.geonet.org.nz/services/quake/quakeml/1.0.1/query?externalRef=2737452

Earthquakes that occurred between the dates 2007-05-17 and 2007-05-18 (inclusive):

http://magma.geonet.org.nz/services/quake/quakeml/1.0.1/query?startDate=2007-05-17&endDate=2007-05-18

Earthquakes that occurred between 10:00 on 2008-08-01 and 10:30 on 2008-08-01:

http://magma.geonet.org.nz/services/quake/quakeml/1.0.1/query?startDate=2008-08-01T10:00:00&endDate=2008-08-01T10:30:00

Earthquakes that occurred between 10:00 on 2008-08-01 and 10:30 on 2008-08-01, together with picks, arrivals, amplitudes and magnitudes:

http://magma.geonet.org.nz/services/quake/quakeml/1.0.1/query?startDate=2008-08-01T10:00:00&endDate=2008-08-01T10:30:00&includePicksAndArrivals=true&includeAmplitudesAndStationMagnitudes=true&includeMultipleMagnitudes=true

Earthquakes that occurred between the dates 2007-05-17 and 2007-05-19 inclusive, within the bounding box latLower=-45, latUpper=-40, longLower=173, longUpper=176 of magnitude up to 7.5 that occurred up to 180 km depth with at least 5 phases recorded and at least 5 stations and with a standard error maximum of 0.15 seconds:

http://magma.geonet.org.nz/services/quake/quakeml/1.0.1/query?startDate=2007-05-17&endDate=2007-05-18&latLower=-45&latUpper=-40&longLower=173&longUpper=176&depthLower=0&depthUpper=180&magnitudeLower=0&magnitudeUpper=7.5&stationsLower=5&phasesLower=5&errorUpper=0.15
*/
function geonetnz_do_search($params) {
  $url = GEONETNZ_ENDPOINT .'?';
  //startDate=2007-05-17&endDate=2007-05-18&latLower=-45&latUpper=-40&longLower=173&longUpper=176&depthLower=0&depthUpper=180&magnitudeLower=0&magnitudeUpper=7.5&
  foreach($params as $k=>$name) {
    $urls .= urlencode("$k=$name&");
  }
  
}


function geonetnz_menu() {
  $items['geonetnz'] = array(
    'title' => t('Earthquake Search'),
    'page callback' => 'geonetnz_search_page',
    'access arguments' => array('access content'),
    'type' => MENU_NORMAL_ITEM,
  );
  $items['geonetnz/timeline'] = array(
    'title' => t('Timeline'),
    'page callback' => 'geonetnz_timeline_page',
    'access arguments' => array('access content'),
  );
  $items['geonetnz/import'] = array(
    'title' => t('Import'),
    'page callback' => 'geonetnz_import',
    'access arguments' => array('import geonet data'),
  );
  return $items;
}

function geonetnz_timeline_page() {
}
function geonetnz_search_page() {
  $output = drupal_get_form('geonetnz_search_form');
  return $output; 
}

function geonetnz_search_form() {
  $form['startDate'] = array(
    '#type' => 'textfield',
    '#title' => t('Start Date'),
    '#description' => t('e.g. 2007-05-17'),
  );
  $form['endDate'] = array(
    '#type' => 'textfield',
    '#title' => t('End Date'),
    '#description' => t('e.g. 2007-05-17'),
  );
  $form['latLower'] = array(
    '#type' => 'textfield',
    '#title' => t('Latitude'),
    '#description' => t('e.g. 2007-05-17'),
  );
  $form['latUpper'] = array(
    '#type' => 'textfield',
    '#title' => t('to Latitude'),
    '#description' => t('e.g. 2007-05-17'),
  );
  $form['longLower'] = array(
    '#type' => 'textfield',
    '#title' => t('Longitude'),
    '#description' => t('e.g. 2007-05-17'),
  );
  $form['longUpper'] = array(
    '#type' => 'textfield',
    '#title' => t('to Longitude'),
    '#description' => t('e.g. 2007-05-17'),
  );
  $form['depthLower'] = array(
    '#type' => 'textfield',
    '#title' => t('Minimum Depth'),
    '#description' => t('e.g. 2007-05-17'),
  );
  $form['depthUpper'] = array(
    '#type' => 'textfield',
    '#title' => t('Maximum Depth'),
    '#description' => t('e.g. 2007-05-17'),
  );
  $form['magnitudeLower'] = array(
    '#type' => 'textfield',
    '#title' => t('Minimum Magnitude'),
    '#description' => t('e.g. 2007-05-17'),
  );
  $form['magnitudeUpper'] = array(
    '#type' => 'textfield',
    '#title' => t('Maximum Magnitude'),
    '#description' => t('e.g. 2007-05-17'),
  );
  
//http://magma.geonet.org.nz/services/quake/quakeml/1.0.1/query?startDate=2007-05-17&endDate=2007-05-18&latLower=-45&latUpper=-40&longLower=173&longUpper=176&depthLower=0&depthUpper=180&magnitudeLower=0&magnitudeUpper=7.5&stationsLower=5&phasesLower=5&errorUpper=0.15

  $form['search'] = array(
    '#value' => t('Search'),
    '#type' => 'submit',
  );
  return $form;
}
function geonetnz_search_form_submit($form_id, $form_state) {
  $startDate = $form_state['values']['startDate'];
  drupal_goto("geonet?startDate=$startDate");
}

function geonetnz_importer() {
  $batch = array(
    'title' => t('Importing Earthquake Data'),
    'operations' => array(
      array('geonet_import_batch_process', array()),
    ),
    'finished' => 'my_finished_callback',
  );
  batch_set($batch);
  // only needed if not inside a form _submit handler :
  batch_process();
}

function geonet_import_batch_process(&$context) {
  if (empty($context['sandbox'])) {
    $context['sandbox']['progress'] = 0;
    $context['sandbox']['current_node'] = 0;
    $context['sandbox']['max'] = db_result(db_query('SELECT COUNT(DISTINCT nid) FROM {node}'));
  }
}